/** Opciones de ciudad (onboarding, formularios de campos, etc.). */
export type CiudadOption = { value: string; label: string }

export const CIUDADES: CiudadOption[] = [
  { value: '', label: 'Selecciona tu ciudad' },
  { value: 'Ciudad de México', label: 'Ciudad de México' },
  { value: 'Guadalajara', label: 'Guadalajara' },
  { value: 'Monterrey', label: 'Monterrey' },
  { value: 'Puebla', label: 'Puebla' },
  { value: 'Tijuana', label: 'Tijuana' },
  { value: 'León', label: 'León' },
  { value: 'Juárez', label: 'Juárez' },
  { value: 'Mérida', label: 'Mérida' },
  { value: 'San Luis Potosí', label: 'San Luis Potosí' },
  { value: 'Querétaro', label: 'Querétaro' },
  { value: 'Hermosillo', label: 'Hermosillo' },
  { value: 'Culiacán', label: 'Culiacán' },
  { value: 'Mexicali', label: 'Mexicali' },
  { value: 'Aguascalientes', label: 'Aguascalientes' },
  { value: 'Morelia', label: 'Morelia' },
  { value: 'Chihuahua', label: 'Chihuahua' },
  { value: 'Saltillo', label: 'Saltillo' },
  { value: 'Torreón', label: 'Torreón' },
  { value: 'Veracruz', label: 'Veracruz' },
  { value: 'Toluca', label: 'Toluca' },
  { value: 'Tuxtla Gutiérrez', label: 'Tuxtla Gutiérrez' },
  { value: 'Cancún', label: 'Cancún' },
  { value: 'Mazatlán', label: 'Mazatlán' },
  { value: 'Tepic', label: 'Tepic' },
  { value: 'Durango', label: 'Durango' },
  { value: 'Oaxaca', label: 'Oaxaca' },
  { value: 'Zacatecas', label: 'Zacatecas' },
  { value: 'Villahermosa', label: 'Villahermosa' },
  { value: 'Colima', label: 'Colima' },
  { value: 'Ciudad Victoria', label: 'Ciudad Victoria' },
  { value: 'Otra', label: 'Otra' },
]
